# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'permtest
#'
#'Performs genewise permutation tests to calculate pvalues for prefiltering.
#'
#'@param genecount An R Numeric vector containing counts for a single gene
#'@param group An R Numeric vector containing group info, typically two integers that correspond to groups
#'@param levels The levels aspect of an R factor for the above group parameter
#'@param nperms The number of permutations to perform
permtest <- function(genecount, group, levels, nperms) {
    .Call(`_DEGage_permtest`, genecount, group, levels, nperms)
}

DEGage_mean <- function(r1, p1, r2, p2) {
    .Call(`_DEGage_DEGage_mean`, r1, p1, r2, p2)
}

DEGage_var <- function(r1, p1, r2, p2) {
    .Call(`_DEGage_DEGage_var`, r1, p1, r2, p2)
}

DEGage_cdf <- function(r1, p1, r2, p2, k) {
    .Call(`_DEGage_DEGage_cdf`, r1, p1, r2, p2, k)
}

