# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'permtest
#'
#'Performs genewise permutation tests to calculate pvalues for prefiltering.
#'
#'@param genecount An R Numeric vector containing counts for a single gene
#'@param group An R Numeric vector containing group info, typically two integers that correspond to groups
#'@param levels The levels aspect of an R factor for the above group parameter
#'@param nperms The number of permutations to perform
permtest <- function(genecount, group, levels, nperms) {
    .Call(`_DEGage_permtest`, genecount, group, levels, nperms)
}

